ftp:
  connect:
    host: "bisecthosting.com"
    port: 99
  login:
    user: "user"
    passwd: "password"
  src_folder: "/"
workdir: "./workdir"
backup_threshold: "24*7"
archive_root: "/media/Element/MCServerBackup"